### ISSUE TITLE
Upload files failed (Forbidden)

### ISSUE THREAD

**Issue by anniewey** [bskim45/fastlane-plugin-google_drive#1]
Below is my verbose logs. Is the issue relate to the plugin or the drive API or did I miss out something? FYI, I had the admin privilege over both drive and project.

`DEBUG [2018-03-27 17:07:13.50]: All plugins are up to date
ERROR [2018-03-27 17:07:13.50]: fastlane finished with errors
DEBUG [2018-03-27 17:07:13.50]: All plugins are up to date
/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/interface.rb:133:in 'user_error!': [!] Upload '../logo.png' failed (FastlaneCore::Interface::FastlaneError)
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in 'method_missing'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-google_drive-0.1.0/lib/fastlane/plugin/google_drive/helper/google_drive_helper.rb:36:in 'rescue in upload_file'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-google_drive-0.1.0/lib/fastlane/plugin/google_drive/helper/google_drive_helper.rb:31:in 'upload_file'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-google_drive-0.1.0/lib/fastlane/plugin/google_drive/actions/google_drive_upload_action.rb:31:in 'block in run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-google_drive-0.1.0/lib/fastlane/plugin/google_drive/actions/google_drive_upload_action.rb:28:in 'each'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-plugin-google_drive-0.1.0/lib/fastlane/plugin/google_drive/actions/google_drive_upload_action.rb:28:in 'run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:257:in 'block (2 levels) in execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in 'execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:236:in 'block in execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:231:in 'chdir'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:231:in 'execute_action'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:157:in 'trigger_action_by_name'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/fast_file.rb:148:in 'method_missing'
	from Fastfile:80:in 'block (2 levels) in parsing_binding'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/lane.rb:33:in 'call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/lane.rb:33:in 'call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:49:in 'block in execute'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:45:in 'chdir'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/runner.rb:45:in 'execute'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/lane_manager.rb:57:in 'cruise_lane'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/command_line_handler.rb:36:in 'handle'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/commands_generator.rb:108:in 'block (2 levels) in run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in 'call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in 'run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in 'run_active_command'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in 'run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in 'run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/commands_generator.rb:333:in 'run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/commands_generator.rb:42:in 'start'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/fastlane/lib/fastlane/cli_tools_distributor.rb:107:in 'take_off'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.87.0/bin/fastlane:20:in '<top (required)>'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in 'load'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in '<main>'`

**Comment by bskim45** [comment]
Did you set google drive credentials correctly from https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md?

Also please check out `bundle exec fastlane action google_drive_upload` to see other options & args

**Comment by anniewey** [comment]
@bskim45 Thanks for the help, turns out I misconfigured the credentials. Another question, how do I specify the file type? The args only require **path to files to be uploaded**. I tried uploading .PNG files but it appeared as DOC file in the drive.

**Comment by bskim45** [comment]
that's strange. The filename should remain unchanged, which is default behavior of Google Drive API.

**Comment by anniewey** [comment]
I found it only applies to image file. I tried uploading APK file and it works fine. Anyhow thanks for your help.
