### ISSUE TITLE
what is 'folder_id'? It return Forbidden

### ISSUE THREAD

**Issue by datvp09** [bskim45/fastlane-plugin-google_drive#10]
I copy 'folder_id' from the drive url. Is it correct? 
The code:

```
upload_to_google_drive(
      drive_keyfile: 'drive-keyfile.json',
      service_account: true,
      folder_id: '15tn9r365lDB1JqtEDsegpIQXczKM5t7v',
      upload_files: ['./app/build/outputs/apk/release/app-x86-release.apk']
)
```

<img width="958" alt="Screen Shot 2020-08-28 at 17 23 47" src="https://user-images.githubusercontent.com/25218577/91551164-f3cbd280-e953-11ea-9fde-9e37b497adcd.png">

and fastlane return

<img width="510" alt="Screen Shot 2020-08-28 at 17 27 13" src="https://user-images.githubusercontent.com/25218577/91551061-c41cca80-e953-11ea-9163-43164f798db4.png">

I have enabled Drive API and placed json keyfile to fastlane folder
Do I need to create Google drive session or something like this?

**Comment by bskim45** [comment]
Did you grant a correct permission of your google drive folder to the service account?

**Comment by datvp09** [comment]
Thankyou so much for remaining me. It's working now

https://blog.stapps.io/gdrive-backups-with-service-accounts/

**Comment by bskim45** [comment]
noice
