### ISSUE TITLE
Unable to update plugin

### ISSUE THREAD

**Issue by zkrige** [bskim45/fastlane-plugin-google_drive#14]
`fastlane update_plugins` isn't updating this plugin. I'm left with this

<img width="341" alt="image" src="https://user-images.githubusercontent.com/968412/99535759-07fef900-29b2-11eb-87d9-1cc58009ddcd.png">

**Comment by zkrige** [comment]
ping @bskim45 - can you advise?

**Comment by bskim45** [comment]
Hi @zkrige,
In latest release v0.5.0, minimum fastlane version is updated to 2.140.0.
Could you update fastlane version to somewhere above 2.140.0 and try again?

**Comment by zkrige** [comment]
```
fastlane --version
fastlane installation at path:
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.169.0/bin/fastlane
-----------------------------
[✔] 🚀 
fastlane 2.169.0

```

**Comment by bskim45** [comment]
Okay. Then we should try something else.

Could you replace `fastlane-plugin-google_drive` in Pluginfile with below:
```
gem 'fastlane-plugin-google_drive', '~> 0.5.0'
```

And do `bundle update` to see there's any constraints blocking the upgrade?

**Comment by zkrige** [comment]
thank you! that seems to have worked
