### ISSUE TITLE
 No actions found  error

### ISSUE THREAD

**Issue by ando0689** [bskim45/fastlane-plugin-google_drive#16]
When I try to add this plugin to my fastlane with command `fastlane add_plugin google_drive`  I get an error saying 
`fastlane-plugin-google_drive              | 0.5.0   | No actions found`

I even tried to install version `0.4.1`, but the same problem exists.

**Comment by dannydanzka** [comment]
Same issue version 0.6.0

**Comment by dannydanzka** [comment]
I solved with next steps

1. Unistall the plugin `sudo gem uninstall fastlane-plugin-google_drive`
2. Uninstall fastlane for all ways, follow this steps.

```
grep -l fastlane /usr/local/bin/*
rm /usr/local/bin/fastlane 
```

for example... delete all routes appearance in the results.

Install fastlane with brew

`brew install fastlane`

Run the fastlane lane and wait install the plugins in your Pluginfile

**Comment by DidahDx** [comment]
I had the same issue with version 0.6.0
Using  `bundle exec` before your fastlane commands seem to bypass the issue

**Comment by hasanmainul** [comment]
Same issue even with the latest version '0.7.0'. Used`bundle exec`, tried with sticking to recommended setup (using brew) as well. Nothing worked. Any suggestion/workaround? 
`` Error loading plugin 'fastlane-plugin-google_drive': Unable to activate google_drive-3.0.7, because googleauth-1.2.0 conflicts with googleauth (>= 0.5.0, < 1.0.0)``

**Comment by hasanmainul** [comment]
Looks like the `google_drive-3.0.7` maintainer needs to fix the dependency. Should solve the issue

**Comment by subash9860** [comment]
@hasanmainul i'm also facing same issue. how do you solve this.

**Comment by bskim45** [comment]
Hi guys, I just release the new version `0.8.0`, which possibly fixes the version conflict with `googleauth`. Please feel free to try the new version and let me know if the problem still exists.
