### ISSUE TITLE
update vs upload

### ISSUE THREAD

**Issue by zkrige** [bskim45/fastlane-plugin-google_drive#28]
@bskim45

I wrote a grunt script to do this for a different app, but the logic could probably work here

search drive for filename
if exists, then get id and update
if not exists, then upload / create file
would it be possible to implement something like this? I'd be happy to share the js code I wrote that does all this if it helps

**Comment by bskim45** [comment]
I just released a new version that introduces new actions for finding existing files in Google Drive. You can do exactly what you want with these newly added actions.
Please refer to the example [Fastfile](fastlane/Fastfile) for working examples.

**Comment by zkrige** [comment]
amazing! thank you!
