### ISSUE TITLE
Unable to fetch values from environment when it is saved as secret file

### ISSUE THREAD

**Issue by Akaur53** [bskim45/fastlane-plugin-google_drive#35]
This works fine when I give the exact location of the file from my system but we need to get it from the environment.
Error. is : Couldn't find config keyfile at path **** 

This is the code I wrote:
keyFile = ENV["GOOGLE_APPLICATION_CREDENTIALS"]
driveId = find_google_drive_file_by_title(
        drive_keyfile: keyFile, // Unable to fetch this value
        service_account: true,
        parent_folder_id: parentFolderId,
        file_title: platform
      )
 upload_to_google_drive(
            drive_keyfile: keyFile,
            service_account: true,
            folder_id: env_variables["BUILD_FOLDER_ID"],
            upload_files: [File.join(folder_path, file)],
          )

**Comment by bskim45** [comment]
What value is assigned to `GOOGLE_APPLICATION_CREDENTIALS` variable? Is it the content of the JSON key file or the path to the key file?

**Comment by Akaur53** [comment]
It is a JSON key file

**Comment by Akaur53** [comment]
Is there a way to give the json data instead of a file path ?

**Comment by bskim45** [comment]
Unfortunately, no. If I have some free time over the weekend, I'll take a look at it. Pull requests are always welcome.

**Comment by SabreRunner** [comment]
> Unfortunately, no. If I have some free time over the weekend, I'll take a look at it. Pull requests are always welcome.

I would also love to have this option. It's much more convenient in Unity Build Automation.

**Comment by SabreRunner** [comment]
I don't know ruby so if this could be done, that will be very helpful.
