### ISSUE TITLE
Docs for creating the drive_key

### ISSUE THREAD

**Issue by vinbhai4u** [bskim45/fastlane-plugin-google_drive#6]
It would be great if you could create a docs/steps for creating the drive_key.json file.
I have been trying this for couple of days. And I couldn't figure it out.

Also how to give access to my google drive too would be great

**Comment by bskim45** [comment]
Please refer to [this guide](https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md) for creating credentials.
I'll also mention it on README.

**Comment by vinbhai4u** [comment]
+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 💥   | upload_to_google_drive | 0           |
+------+------------------------+-------------+

[12:53:15]: fastlane finished with errors

[!] Invalid Google Drive credentials


I am getting this error from the above doc. 
I tried the below section
https://github.com/gimite/google-drive-ruby/blob/master/doc/authorization.md#on-behalf-of-the-user-who-accesses-your-web-app-web-based-authorization

**Comment by vinbhai4u** [comment]
Gave 

> service_account: false,

and it worked, showed a weblink to clicked on the same and was able to upload. 

Also is it possible to get the uploaded files sharable link?

**Comment by bskim45** [comment]
The list of links to uploaded files are returned as an output of the upload action. But those are not shareable since you need to mark files as sharable to get shared links.
