### ISSUE TITLE
Unable to create folder and upload into it

### ISSUE THREAD

**Issue by jrogiers-grio** [bskim45/fastlane-plugin-google_drive#7]
`  desc "Build Debug APK & Upload to Google Drive"
  lane :buildDebugDeploy do
    gradle(task: "clean assembleDebug --stacktrace")

    new_id = create_google_drive_folder(
      drive_keyfile: 'google-service-account.json',
      folder_id: folder_id,
      folder_title: 'git_branch'
    )

    upload_google_drive(
      drive_keyfile: 'google-service-account.json',
      service_account: true,
      folder_id: new_id.resource_id,
      upload_files: ['app/build/outputs/apk/debug/app-debug.apk']
    )
  end`

With this example I am trying to upload files into a newly created folder made up of the git branch. Sadly this keeps failing. The new folder gets created successfully, but when the upload_google_drive command runs, it fails.

> [15:43:18]: ------------------
[15:43:18]: Creating git_branch
[15:43:20]: Success
[15:43:20]: ------------------
[15:43:20]: ---------------------------------
[15:43:20]: --- Step: upload_google_drive ---
[15:43:20]: ---------------------------------
[15:43:20]: Using config file: google-service-account.json
[15:43:20]: notFound: File not found: folder:1Qd6P5421VrcnU1[truncated].
+-------------------------------------+--------------------------------------+
|                                Lane Context                                |
+-------------------------------------+--------------------------------------+
| DEFAULT_PLATFORM                    | android                              |
| PLATFORM_NAME                       | android                              |
| LANE_NAME                           | android buildDebugDeploy             |
| GDRIVE_CREATED_FOLDER_ID            | 1Qd6P5421VrcnU1[truncated]    |
| GDRIVE_CREATED_FOLDER_URL           | https://drive.google.com/drive/fold  |
|                                     | ers/1Qd6P5421VrcnU1[truncated]  |
|                                     | au                                   |
+-------------------------------------+--------------------------------------+
[15:43:20]: File with id 'folder:1Qd6P5421VrcnU1[truncated]' not found in Google Drive

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 12          |
| 2    | default_platform       | 0           |
| 3    | gradle                 | 65          |
| 4    | create_google_drive_f  | 2           |
|      | older                  |             |
| 💥   | upload_google_drive    | 0           |
+------+------------------------+-------------+

[15:43:20]: fastlane finished with errors

[!] File with id 'folder:1Qd6P5421VrcnU1[truncated]' not found in Google Drive

**Comment by jrogiers-grio** [comment]
Update on this, specifying the subsequent folder_id as a string fails. But if you use the SharedValues key for it, then it works. This is more a note for anyone else who might've experienced this, but this is still definitely a bug.

`      create_google_drive_folder(
        drive_keyfile: 'google-service-account.json',
        folder_id: folder_id,
        folder_title: 'git_branch'
      )
      upload_google_drive(
        drive_keyfile: 'google-service-account.json',
        folder_id: lane_context[SharedValues::GDRIVE_CREATED_FOLDER_ID],
        upload_files: ['app/build/outputs/apk/debug/app-debug.apk']
      )`

**Comment by bskim45** [comment]
@jrogiers-grio I'm afraid this is not a bug. `SharedValues::GDRIVE_CREATED_FOLDER_ID` contains the ID of newly created folder, however, the return value of `create_google_drive_folder` is `GoogleDrive::Collection` object. This is clearly stated in the description of the fastlane action(`fastlane actions create_google_drive_folder`). If you want to extract the folder ID from the return value itself, you might want to do like `folder_id = new_folder.resource_id.split(':').last`.
