### ISSUE TITLE
unknown keyword: supports_all_drives

### ISSUE THREAD

**Issue by jaySC123** [bskim45/fastlane-plugin-google_drive#9]
i'm new to gitlab ci + fastlane, encountered a few errors when trying to use this plugin to either create a new folder or upload a file to a folder on a shared drive. the operation is done on a service account, with which the folder is shared with and also the account has permissions to edit. the errors are:

"unknown keyword: supports_all_drives"

followed by:

"File with id 'xxx' not found in Google Drive"

logs as shown below:

[02:15:57]: ----------------------------------------
[02:15:57]: --- Step: create_google_drive_folder ---
[02:15:57]: ----------------------------------------
[02:15:57]: Using config file: google_drive_key.json
[02:15:57]: unknown keyword: supports_all_drives
+------------------+------------------------+
|               Lane Context                |
+------------------+------------------------+
| DEFAULT_PLATFORM | android                |
| PLATFORM_NAME    | android                |
| LANE_NAME        | android upload_apk_dev |
+------------------+------------------------+
[02:15:57]: File with id '1LOFlFqoF0mImFY80Yhm8-hiBJffB_ufK' not found in Google Drive

is this due to permissions settings (esp for shared drives), or dependency issues? coz i googled for "support_all_drives" and it seems it is needed for the google drive api to enable using shared drives. thanks.

**Comment by bskim45** [comment]
This plugin uses `google_drive` gem to communicate with Google Drive API. It seems like `supports_all_drives` is new feature flag and the updated gem do recognize `supports_all_drives`, however it still requires some fix to work properly. (https://github.com/gimite/google-drive-ruby/issues/360 <https://github.com/gimite/google-drive-ruby/issues/360>)

Unfortunately, I have no chance to try our the shard drive feature, so we have to wait until `google_drive` gem properly support the shard drive or someone post a pr the fix.

**Comment by bskim45** [comment]
This plugin uses `google_drive` gem to communicate with Google Drive API. It seems like `supports_all_drives` is new feature flag and the updated gem do recognize `supports_all_drives`, however it still requires some fix to work properly. (https://github.com/gimite/google-drive-ruby/issues/360 <https://github.com/gimite/google-drive-ruby/issues/360>)

Unfortunately, I have no chance to try out new shard drive feature, so we have to wait until `google_drive` gem properly support the shard drive or someone post a pr for the fix.

**Comment by jaySC123** [comment]
ok noted, i'll have to find a way around it for now then. thanks for the swift reply.

**Comment by bskim45** [comment]
No problem. I'll keep an eye on gem updates.

**Comment by bskim45** [comment]
Hi, I just released new version `v0.5.0` which recognizes `supports_all_drives`.

As I mentioned, I have no chance to actually try out this on the shared drive. Please try out and let me know if there's any problem.

**Comment by jaySC123** [comment]
hi,

thanks alot for informing, unfortunately we have since shifted to aws s3
which works much better for our use case, so i'm no longer able to test it
out as well. still, thanks alot for informing me and for the great effort!

regards
